### ISSUE TITLE
Can't find 'env' file

### ISSUE THREAD

**Issue by gdcohan** [GetStream/stream-react-example#1]
When I run `node index.js` in the `api` directory, I get the following error: 
`Error: ENOENT: no such file or directory, open 'env'`

Changing the `path` in `index.js` to point directly to the `env.sh` file seems to fix this.

**Comment by astrotars** [comment]
Hey @gdcohan, great catch! We're using the [dot-env node module](https://www.npmjs.com/package/dotenv) to load in the environment. 

That said, you'll in fact need a file named `env` inside of the API directory. Feel free to drop the `.sh` extension and `export` decorations. 

We're working on a better fix for this and will be in touch shortly.

**Comment by davidvenin** [comment]
Related to this bug, after fixing this a nice error appear :
```
 const defaultAllowHeaders = ['Authorization', 'Content-Type'];
    ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/david/dev-env/stream-react-example/api/index.js:56:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by astrotars** [comment]
@gdcohan, we've removed the `dot-env` dependency. Please run `source ../env.sh; node index.js` to get your API up and running. Cheers!

**Comment by qbunt** [comment]
AWESOME series, great to see a full scale real application instead of another ToDo. Kudos!
