### ISSUE TITLE
Intermittent demo breakage (after FB Connect)

### ISSUE THREAD

**Issue by dwightgunning** [GetStream/stream-react-example#18]
The demo seems to be breaking intermittently after authorizing Cabin via Facebook Connect.

The following is logged to the browser console:

```
external "react":1 Uncaught (in promise) TypeError: Cannot read property 'charAt' of null
    at http://cabin.getstream.io:3000/js/app.js:61765:48
    at Array.map (native)
    at Onboarding.render (http://cabin.getstream.io:3000/js/app.js:61751:35)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://cabin.getstream.io:3000/js/app.js:15609:35)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://cabin.getstream.io:3000/js/app.js:15635:33)
    at ReactCompositeComponentWrapper.performInitialMount (http://cabin.getstream.io:3000/js/app.js:15145:31)
    at ReactCompositeComponentWrapper.mountComponent (http://cabin.getstream.io:3000/js/app.js:15038:22)
    at Object.mountComponent (http://cabin.getstream.io:3000/js/app.js:8167:36)
    at ReactDOMComponent.mountChildren (http://cabin.getstream.io:3000/js/app.js:14246:45)
    at ReactDOMComponent._createInitialChildren (http://cabin.getstream.io:3000/js/app.js:11235:33)```

**Comment by dwightgunning** [comment]
Resolved with PR #21.
