### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by kinjalgiri** [GetStream/stream-react-example#8]
```
[root@JLLT002 api]# node -v
v0.10.42
[root@JLLT002 api]# source ../env.sh; node index.js

/usr/share/nginx/react/stream-react-example/api/lib/cors/index.js:5
    const defaultAllowHeaders = ['Authorization', 'Content-Type'];
    ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/nginx/react/stream-react-example/api/index.js:51:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[root@JLLT002 api]#
```

I also tried updating nodejs but same error again and again. I am using Cent OS 6.

**Comment by astrotars** [comment]
@kinjalgiri what version of node.js are you running? have you tried passing in the harmony flag in when starting node? https://nodejs.org/en/docs/es6/

**Comment by kinjalgiri** [comment]
```
[root@JLLT002 api]# node -v
v0.10.42
```

For --harmony flag, I will give it a try and let you know here.

**Comment by astrotars** [comment]
You're way out of date. I'd recommend node 5.x.
